### ISSUE TITLE
Extraneous leading sample inserted by median filter

### ISSUE THREAD

**Issue by ClayMontgomery** [kergoth/tslib#95] opened 2017-05-03 21:55 UTC
I'm seeing an issue with the median filter. It usually inserts a leading sample with uninitialized x and y values at the start of each set of samples from each touch gesture. It does this most of the time, but not always. The pressure value is always 0 and the x and y values are garbage, but always the same pair of values. I understand x and y should not be valid when the pressure is 0, but with other filters, the 0 pressure sample only occurs once at the end of a sequence of samples. With the median filter, the 0 pressure sample occurs at the start and again at the end of each gesture sequence. I am calling ts_read_mt() in non-blocking mode and always requesting 10 samples. I usually get between 1 to 5 samples per call.  I am using tslib 1.9 and the complete list of filters I am using are:

module_raw input
module pthres pmin=1
module median depth=6
module linear

Regards, Clay

**Comment by merge** [comment] 2017-05-04 00:55
You're right. Actually it should be depth/2 of those zero-samples. In your case actually 5/2 (median only works for odd numbers depths), which becomes 2. So two, not only one. Is that correct?

Thanks for reporting this! It can't indeed be the intended behaviour. I'll have a look as time permits, but I'm confident that this will be fixed for the 1.10 release.

**Comment by merge** [comment] 2017-05-04 08:36
Please re-open if you can test and still have problems with it. And if you want to, give me your email address to put in the THANKS file. so, thanks.

**Closed** 2017-05-04 08:36 UTC

**Comment by merge** [comment] 2017-05-04 22:49
just fyi, there's already the 1.10-rc1 tarball release in case you want to test that fix early.
